name: iOS binary build & upload to TestFlight

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Create .env file
        run: |
          echo "${{ secrets.APP_ENV_FILE }}" > .env.default
      - name: Install bundler
        run: gem install bundler
      - name: Install fastlane dependencies
        run: bundle install
      - name: Show deeper structure
        run: |
          pwd
          ls -la
          ls -la CardSafe || true
          ls -la ios || true
      - name: Build & upload iOS binary
        run: |
          bundle exec fastlane build_upload_testflight
      - name: Upload Xcode logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-archive-log
          path: build/logs/**/*.log
        env:
          FASTLANE_XCBEAUTIFY: "false"
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}